sonar.projectKey=ponos-os_smart-novel
sonar.organization=ponos-os

sonar.sources=apps/backend/src,apps/frontend/src
sonar.exclusions=**/generated/**,**/dist/**,**/*.stories.tsx,apps/backend/src/shared/beatrice/graphql-env.d.ts

sonar.javascript.lcov.reportPaths=coverage/apps/backend/lcov.info,coverage/apps/frontend/lcov.info
sonar.sourceEncoding=UTF-8
