query GetNovel($id: ID!) {
  novel(id: $id) {
    id
    name
    author
    category
    state
    coverUrl
    description
    allowedActions
    chaptersConnection(
      first: 100
      orderBy: { field: CHAPTER_NUMBER, direction: ASC }
    ) {
      edges {
        cursor
        node {
          id
          title
          chapterNumber
          createdAt
          narrationStatus
          narrationUrl
        }
      }
      pageInfo {
        endCursor
        hasNextPage
        hasPreviousPage
        startCursor
      }
      totalCount
    }
    firstChapter {
      id
    }
    lastPublishedChapter {
      id
    }
  }
}

query GetChapter($novelId: ID!, $chapterId: ID!) {
  novel(id: $novelId) {
    chapter(id: $chapterId) {
      id
      novelId
      title
      content
      createdAt
      updatedAt
      contentUpdatedAt
      narrationStatus
      narrationUrl
      next {
        id
      }
      previous {
        id
      }
    }
  }
}

mutation UpdateContent(
  $id: ID!
  $content: String!
  $expectedContentUpdatedAt: String!
) {
  updateContent(
    id: $id
    content: $content
    expectedContentUpdatedAt: $expectedContentUpdatedAt
  ) {
    id
    content
  }
}

mutation UpdateChapter(
  $id: ID!
  $input: UpdateChapterInput!
  $expectedUpdatedAt: String!
) {
  updateChapter(
    id: $id
    input: $input
    expectedUpdatedAt: $expectedUpdatedAt
  ) {
    id
    title
  }
}

mutation UpdateChapterAndContent(
  $id: ID!
  $content: String!
  $expectedContentUpdatedAt: String!
  $input: UpdateChapterInput!
  $expectedUpdatedAt: String!
) {
  updateContent(
    id: $id
    content: $content
    expectedContentUpdatedAt: $expectedContentUpdatedAt
  ) {
    id
    content
  }
  updateChapter(
    id: $id
    input: $input
    expectedUpdatedAt: $expectedUpdatedAt
  ) {
    id
    title
  }
}

mutation GenerateChapterAudio($id: ID!) {
  generateChapterAudio(id: $id) {
    status
    narrationUrl
  }
}
